name: example
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  matrix4_transform: ^2.0.1
  dashbook: ^0.1.6
  flutter_markdown: ^0.6.9
  flutter_highlight: 0.7.0
  fluttertoast: 8.0.9
  flutter_color_picker_wheel:
    path: ..
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

