name: flutter_color_picker_wheel
description: A Wheel Shapde Color Picker written fully in dart
version: 0.0.1
homepage:  https://github.com/KexinLu/FlutterColorPickerWheel

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  matrix4_transform: ^2.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: